zeppelin:
   version: 0.8.1
   zeppelin_install_dir: /usr/local
   download_location: http://mirrors.estointernet.in/apache/zeppelin
   spark_cassandra_connector_location: /root/spark-cassandra-connector-assembly-2.4.1-16-gc94f154.jar
   user: "zeppelin"
   spark_url: spark://{{ groups['spark-master'][0] }}:7077
   user_shell: "/bin/false"
